export enum PermissionCategory {
  COURSE_MANAGEMENT = 'COURSE_MANAGEMENT',

  EXAM_MANAGEMENT = 'EXAM_MANAGEMENT',

  QUESTION_BANK_MANAGEMENT = 'QUESTION_BANK_MANAGEMENT',

  SUBMISSION_REVIEW = 'SUBMISSION_REVIEW',

  USER_ACCOUNT_MANAGEMENT = 'USER_ACCOUNT_MANAGEMENT',

  SYSTEM_ADMINISTRATION = 'SYSTEM_ADMINISTRATION',
}
