package com.example.leavestech.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AuthUserAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAuthUserAllPropertiesEquals(AuthUser expected, AuthUser actual) {
        assertAuthUserAutoGeneratedPropertiesEquals(expected, actual);
        assertAuthUserAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAuthUserAllUpdatablePropertiesEquals(AuthUser expected, AuthUser actual) {
        assertAuthUserUpdatableFieldsEquals(expected, actual);
        assertAuthUserUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAuthUserAutoGeneratedPropertiesEquals(AuthUser expected, AuthUser actual) {
        assertThat(actual)
            .as("Verify AuthUser auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAuthUserUpdatableFieldsEquals(AuthUser expected, AuthUser actual) {
        assertThat(actual)
            .as("Verify AuthUser relevant properties")
            .satisfies(a -> assertThat(a.getUsername()).as("check username").isEqualTo(expected.getUsername()))
            .satisfies(a -> assertThat(a.getEmail()).as("check email").isEqualTo(expected.getEmail()))
            .satisfies(a -> assertThat(a.getPhoneNumber()).as("check phoneNumber").isEqualTo(expected.getPhoneNumber()))
            .satisfies(a -> assertThat(a.getFirstName()).as("check firstName").isEqualTo(expected.getFirstName()))
            .satisfies(a -> assertThat(a.getLastName()).as("check lastName").isEqualTo(expected.getLastName()))
            .satisfies(a -> assertThat(a.getPassword()).as("check password").isEqualTo(expected.getPassword()))
            .satisfies(a -> assertThat(a.getEnabled()).as("check enabled").isEqualTo(expected.getEnabled()))
            .satisfies(a -> assertThat(a.getUserType()).as("check userType").isEqualTo(expected.getUserType()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAuthUserUpdatableRelationshipsEquals(AuthUser expected, AuthUser actual) {
        assertThat(actual)
            .as("Verify AuthUser relationships")
            .satisfies(a -> assertThat(a.getRoles()).as("check roles").isEqualTo(expected.getRoles()));
    }
}
