package com.example.leavestech.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CodingQuestionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCodingQuestionAllPropertiesEquals(CodingQuestion expected, CodingQuestion actual) {
        assertCodingQuestionAutoGeneratedPropertiesEquals(expected, actual);
        assertCodingQuestionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCodingQuestionAllUpdatablePropertiesEquals(CodingQuestion expected, CodingQuestion actual) {
        assertCodingQuestionUpdatableFieldsEquals(expected, actual);
        assertCodingQuestionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCodingQuestionAutoGeneratedPropertiesEquals(CodingQuestion expected, CodingQuestion actual) {
        assertThat(actual)
            .as("Verify CodingQuestion auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCodingQuestionUpdatableFieldsEquals(CodingQuestion expected, CodingQuestion actual) {
        assertThat(actual)
            .as("Verify CodingQuestion relevant properties")
            .satisfies(a -> assertThat(a.getTitle()).as("check title").isEqualTo(expected.getTitle()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getMaxScore()).as("check maxScore").isEqualTo(expected.getMaxScore()))
            .satisfies(a -> assertThat(a.getStarterCode()).as("check starterCode").isEqualTo(expected.getStarterCode()))
            .satisfies(a -> assertThat(a.getLanguage()).as("check language").isEqualTo(expected.getLanguage()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCodingQuestionUpdatableRelationshipsEquals(CodingQuestion expected, CodingQuestion actual) {
        assertThat(actual)
            .as("Verify CodingQuestion relationships")
            .satisfies(a -> assertThat(a.getExams()).as("check exams").isEqualTo(expected.getExams()));
    }
}
