package com.example.leavestech.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SubmissionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSubmissionAllPropertiesEquals(Submission expected, Submission actual) {
        assertSubmissionAutoGeneratedPropertiesEquals(expected, actual);
        assertSubmissionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSubmissionAllUpdatablePropertiesEquals(Submission expected, Submission actual) {
        assertSubmissionUpdatableFieldsEquals(expected, actual);
        assertSubmissionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSubmissionAutoGeneratedPropertiesEquals(Submission expected, Submission actual) {
        assertThat(actual)
            .as("Verify Submission auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSubmissionUpdatableFieldsEquals(Submission expected, Submission actual) {
        assertThat(actual)
            .as("Verify Submission relevant properties")
            .satisfies(a -> assertThat(a.getSubmittedCode()).as("check submittedCode").isEqualTo(expected.getSubmittedCode()))
            .satisfies(a -> assertThat(a.getScore()).as("check score").isEqualTo(expected.getScore()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getSubmissionDate()).as("check submissionDate").isEqualTo(expected.getSubmissionDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSubmissionUpdatableRelationshipsEquals(Submission expected, Submission actual) {
        assertThat(actual)
            .as("Verify Submission relationships")
            .satisfies(a -> assertThat(a.getStudent()).as("check student").isEqualTo(expected.getStudent()))
            .satisfies(a -> assertThat(a.getQuestion()).as("check question").isEqualTo(expected.getQuestion()))
            .satisfies(a -> assertThat(a.getExam()).as("check exam").isEqualTo(expected.getExam()));
    }
}
